### PR TITLE
ShapeContainer still needs work on

### PR DESCRIPTION
**Pull request by alternatebow**

### CODE REVIEW

**Comment by karlnicholas** [comment]
I was thinking of removing it.

**Comment by alternatebow** [comment]
So what do we replace it with? Don't we still need it to keep track of whatever the shapes need?

**Comment by karlnicholas** [comment]
Yea, we could move all the variables into RecurseProgram,  but I suppose it's cleaner with the two separate classes. Let me look at what you have. Also, I think Jill is going to work on the minimum radius issue.

**Comment by karlnicholas** [comment]
Let me ask you this: What work do you think needs to be done on ShapeContainer?

**Comment by karlnicholas** [comment]
It looks fine to me ...

**Comment by alternatebow** [comment]
Yeah... I think so too. I was kinda struggling to see what more could be done to it. And I do like having it split into two separate classes, rather than being smushed into one.

**Comment by karlnicholas** [comment]
You're making a new pull request?

**Comment by karlnicholas** [comment]
You've got branch updates that need a pull request.

**Comment by alternatebow** [comment]
I do?

**Comment by alternatebow** [comment]
Aw crap, I accidentally made a pull request to a new branch instead of the master. It was called "Finaldraft"

**Comment by karlnicholas** [comment]
branch is still there. Go online and create a new pull request for it.

**Pull request merged**
