### PR TITLE
Update Animation.java

### PR DESCRIPTION
**Pull request by jillHuang7**
add comments for animation

### CODE REVIEW

**Comment by karlnicholas** [comment]
Review: The comments are taken from the Javadoc's about the Runnable, which does not describe what the Object actually in the context of the application. These comments do not document the Animation class. While I understand that English is a second language for many, more effort must be made to write sensible English when writing at the College level.

**Comment by karlnicholas** [comment]
PS> I'm happy to spend some time explaining how the program works since that will be important for documenting properly.

**Comment by alternatebow** [comment]
Anyone knows how the git rebate method works? Specifically how to avoid
merge conflicts?

**Comment by karlnicholas** [comment]
I assume you mean rebase? I don't know it well enough to explain it well. If you're having merge problems, perhaps you want to pus your

**Pull request merged**
