### PR TITLE
Color selector

### PR DESCRIPTION
**Pull request by alternatebow**
So this feature will change the colors of the polygons based on the radius. I haven't found out how to gray out the color drop down menu yet. Still working on that. The radii chosen are just somewhat arbitrary, so that might need to be changed as well. Watching the animation was like having epilepsy.

### CODE REVIEW

**Comment by karlnicholas** [comment]
Maybe better put up a confirmation dialog with a warning! :)

Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by karlnicholas** [comment]
Don't worry about greying out the button. The next classroom section on sorting is long and complicated, so let's call this well done (after comments) and wrap it up.

Get Outlook for <https://aka.ms/o0ukef>

**Comment by alternatebow** [comment]
Alright cool. This certainly was a learning experience for me. I appreciate
that.

**Comment by karlnicholas** [comment]
Glad to hear it. Me too, I'm getting more exposure to git.  I changed the color selector to be counter based instead of radius based so it didn't blink so much. The final result is pretty nice I think.

**Comment by alternatebow** [comment]
Looks pretty good. We good to submit?

**Comment by karlnicholas** [comment]
Jill will be adding comments. Comments are important.

**Comment by jillHuang7** [comment]
Please let me know if all of my comments are understandable....
If it was not clear, I would re-write again.
Thank you so much!!

**Pull request merged**
